# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Cholor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cholor
    pod 'Hero', '~> 1.4'
    pod 'AudioKit', '~> 4.5'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    
end
