//: ## Cholor
//: ### Tabla de Contenidos
//: 1. [Constantes y Variables](Constantes%20Variables)
//: 1. [Funciones](Funciones)
//: 1. [Manejo de Errores](Manejo%20Errores)
//: 1. [Notificación](Notificacion)
//: 1. [Clases y Estructuras](Clases%20y%20Estructuras)
//: 1. [POO y POP](POO%20y%20POP)
//: 1. [Layer](Layer)
//: 1. [Cálculos matemáticos básicos](Calculos%20matematicos%20basicos)
//: 1. [Animación Mostrar](Animacion%20Mostrar)
//: 1. [Animación Mostrar con Retardo](Animacion%20Mostrar%20Retardo)
//: 1. [Animación Mover hacia arriba](Animacion%20Mover)
//: 1. [Animación Mover hacia arriba y Volver](Animacion%20Mover%20Volver)
//: 1. [Animación Aumentar tamaño](Animacion%20Aumentar)
//: 1. [Animación Girar](Animacion%20Girar)
//: 1. [Gestos](Gestos)
//: 1. [Arrays y Diccionarios](Arrays y Diccionarios)
//: 1. [Transformando Arrays (Programación funcional)](Transformando%20Arrays)
//: 1. [Dinamicas](Dinamicas)
//: 1. [Delegado Colisiones](Delegado%20Colisiones)
//: 1. [Comportamiento empuje con el gesto de pulsar](PushBehavior%20con%20Arrastrar)
//: 1. [Botón dinámico](Boton%20dinamico)
//: 1. [Dibujar](Dibujar)

